const mongoose =require("mongoose");

const ReservationDetailsSchema=new mongoose.Schema({
    refNo:{
        type:Number,
        required:true
    },
    guestEmail:{
        type:String,
        required:true,     
    },
    guestContact:{
        type:String,
        required:true,
        minlength:10
    },
    billingGuestName:{
        type:String,
        required:true
    },
    roomInfo:{
        type:Object,
        roomId:Number,
        adult:String,
        child:String,
        ratePlan:String,
        roomPrice:String,
        roomType:String,
        guestName:String,
        roomNo:Number
    },
    advancePayment:{
        type:Number,
        null:true
    },
    lastPayment:{
        type:Number,
        required:true
    },
    totalPrice:{
        type:Number,
        required:true 
    },
    roomCharges:{
        type:Number,
        required:true 
    },
    tax:{
        type:Number,
        required:true 
    },
    paymentMode:{
        type:String,
        required:true,
    },
    bookingInfo:{
        type:String,
        required:true,
    },
    agent:{
        type:String,
        required:true,
    },
    bookingType:{
        type:String,
        required:true
    },
    checkInDate:{
        type:String,
        required:true
    },
    checkOutDate:{
        type:String,
        required:true
    },
    nights:{
        type:Number,
        required:true
    },
    hotelEmail:{
        type:String,
        required:true
    },
    hotelName:{
        type:String,
        required:true
    },
    taxInc:{
        type:Boolean,
        required:true
        
    },
    billingUser:{
        type:String,
        required:true
    },

    hotelId:{
        type:String,
        required:true
    },
    isCheckedIn:{
        type:Boolean,
        default:false
    }
    
},{timestamps:true})

module.exports=mongoose.model("ReservationDetails",ReservationDetailsSchema);